apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/ocp-example-dot-net-app-images/example-dot-net-app:latest
    newTag: "43e81f0b69dde23ce41223f6f154f11b9b98a084"
patches:
  - path: route-patch.yaml
    target:
      kind: Route
      name: example-dot-net-app
